# Generated by Django 3.2.3 on 2021-07-30 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='')),
                ('image', models.ImageField(blank=True, null=True, upload_to='about_us_image', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'О нас',
                'verbose_name_plural': 'O нас',
            },
        ),
        migrations.CreateModel(
            name='Advantages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True, verbose_name='Заголовок')),
                ('image', models.ImageField(blank=True, null=True, upload_to='advantages', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Наши преимущества',
                'verbose_name_plural': 'Наши преимущества',
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Ф.И.О')),
                ('mail', models.CharField(max_length=255, verbose_name='Почта')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер Телефона')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время Заявки')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('mail', models.CharField(max_length=255, verbose_name='Почта')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер Телефона')),
                ('phone_number2', models.CharField(max_length=20, verbose_name='Номер Телефона')),
                ('whatsapp', models.CharField(blank=True, max_length=200, verbose_name='Whatsapp')),
                ('telegram', models.CharField(blank=True, max_length=200, verbose_name='Telegram')),
                ('instagram', models.CharField(max_length=55, verbose_name='Instagram')),
                ('twitter', models.CharField(max_length=55, verbose_name='Twitter')),
                ('facebook', models.CharField(max_length=55, verbose_name='Facebook')),
            ],
            options={
                'verbose_name': 'Контакты',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True, verbose_name='Заголовок')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('age', models.CharField(max_length=255, null=True, verbose_name='Возраст')),
                ('time', models.CharField(max_length=15, null=True, verbose_name='Продолжительность Занятия')),
                ('image', models.ImageField(blank=True, null=True, upload_to='course', verbose_name='Изображение')),
                ('duration', models.IntegerField(choices=[(1, '1 месяц'), (2, '2 месяц'), (3, '3 месяц'), (4, '4 месяц'), (5, '5 месяц'), (6, '6 месяц')], default=0, verbose_name='Длительность Курсов')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('date', models.CharField(max_length=255, verbose_name='Дата Провождения Мероприятия')),
                ('location', models.CharField(max_length=255, verbose_name='Место Мероприятия')),
                ('image', models.ImageField(blank=True, null=True, upload_to='event', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(null=True, verbose_name='Вопрос')),
                ('answer', models.TextField(null=True, verbose_name='Ответ')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQ',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Ф.И.О')),
                ('image', models.ImageField(blank=True, null=True, upload_to='feedback', verbose_name='Изображение')),
                ('message', models.TextField(verbose_name='Текст')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер Телефона')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialty', models.CharField(max_length=255, verbose_name='Специальность')),
                ('name', models.CharField(max_length=255, verbose_name='Ф.И.О')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='mentor', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Ментора',
                'verbose_name_plural': 'Менторы',
            },
        ),
        migrations.CreateModel(
            name='FAQCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500, null=True, verbose_name='Вопрос')),
                ('answer', models.CharField(max_length=500, null=True, verbose_name='Ответ')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Курсы', to='codifyteens.course')),
            ],
            options={
                'verbose_name': 'FAQ (Курс)',
                'verbose_name_plural': 'FAQ (Курсы)',
            },
        ),
        migrations.CreateModel(
            name='CourseImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True, verbose_name='Заголовок')),
                ('images', models.ImageField(upload_to='course1', verbose_name='Изображение')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='codifyteens.course')),
            ],
            options={
                'verbose_name': 'Изображение (Курсы)',
                'verbose_name_plural': 'Изображении (Курсы)',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='mentor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='codifyteens.mentor'),
        ),
        migrations.CreateModel(
            name='AboutUsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок')),
                ('images', models.ImageField(upload_to='about-us', verbose_name='Изображение')),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='codifyteens.aboutus')),
            ],
            options={
                'verbose_name': 'Изображение (О нас)',
                'verbose_name_plural': 'Изображении (О нас)',
            },
        ),
    ]
