# Generated by Django 3.2.3 on 2021-11-12 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'О нас',
                'verbose_name_plural': 'О нас',
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('name_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('name_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('image', models.ImageField(upload_to='certificate-photos/', verbose_name='Сертификаты')),
            ],
            options={
                'verbose_name': 'Сертификат',
                'verbose_name_plural': 'Сертификаты',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True, verbose_name='Название курса')),
                ('title_ru', models.CharField(blank=True, max_length=250, null=True, verbose_name='Название курса')),
                ('title_en', models.CharField(blank=True, max_length=250, null=True, verbose_name='Название курса')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Краткое описание')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Краткое описание')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Краткое описание')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Полное описание')),
                ('text_ru', models.TextField(blank=True, null=True, verbose_name='Полное описание')),
                ('text_en', models.TextField(blank=True, null=True, verbose_name='Полное описание')),
                ('age', models.CharField(max_length=250, verbose_name='Возрастная категория')),
                ('duration', models.CharField(blank=True, max_length=250, null=True, verbose_name='Продолжительность курса')),
                ('duration_ru', models.CharField(blank=True, max_length=250, null=True, verbose_name='Продолжительность курса')),
                ('duration_en', models.CharField(blank=True, max_length=250, null=True, verbose_name='Продолжительность курса')),
                ('schedule', models.CharField(blank=True, max_length=250, null=True, verbose_name='График занятий')),
                ('schedule_ru', models.CharField(blank=True, max_length=250, null=True, verbose_name='График занятий')),
                ('schedule_en', models.CharField(blank=True, max_length=250, null=True, verbose_name='График занятий')),
                ('price', models.CharField(blank=True, max_length=250, null=True, verbose_name='Стоимость курса')),
                ('price_ru', models.CharField(blank=True, max_length=250, null=True, verbose_name='Стоимость курса')),
                ('price_en', models.CharField(blank=True, max_length=250, null=True, verbose_name='Стоимость курса')),
                ('image', models.ImageField(blank=True, null=True, upload_to='gallery_images/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('title_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('title_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='Время')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес')),
                ('location_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес')),
                ('location_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес')),
                ('image', models.ImageField(upload_to='events-images/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, max_length=250, null=True, verbose_name='Текст вопроса')),
                ('question_ru', models.CharField(blank=True, max_length=250, null=True, verbose_name='Текст вопроса')),
                ('question_en', models.CharField(blank=True, max_length=250, null=True, verbose_name='Текст вопроса')),
                ('answer', models.TextField(blank=True, null=True, verbose_name='Текст ответа')),
                ('answer_ru', models.TextField(blank=True, null=True, verbose_name='Текст ответа')),
                ('answer_en', models.TextField(blank=True, null=True, verbose_name='Текст ответа')),
            ],
            options={
                'verbose_name': 'Часто задаваемые вопросы',
                'verbose_name_plural': 'Часто задаваемые вопросы',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя')),
                ('name_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя')),
                ('name_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя')),
                ('image', models.ImageField(blank=True, null=True, upload_to='feedbacks-photos/', verbose_name='Фотография')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Отзыв')),
                ('comment_ru', models.TextField(blank=True, null=True, verbose_name='Отзыв')),
                ('comment_en', models.TextField(blank=True, null=True, verbose_name='Отзыв')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=255, verbose_name='Числовое значение')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Краткое описание')),
                ('description_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Краткое описание')),
                ('description_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Краткое описание')),
            ],
            options={
                'verbose_name': 'О нас в цифрах',
                'verbose_name_plural': 'О нас в цифрах',
            },
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя')),
                ('first_name_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя')),
                ('first_name_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Фамилия')),
                ('last_name_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Фамилия')),
                ('last_name_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Фамилия')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Краткое описание')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Краткое описание')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Краткое описание')),
                ('image', models.ImageField(upload_to='mentors-photos/', verbose_name='Фотография')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentors', to='codifyteens.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Ментор',
                'verbose_name_plural': 'Менторы',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='gallery_images/', verbose_name='Фотография')),
                ('about_us', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='codifyteens.aboutus')),
            ],
            options={
                'verbose_name': 'Галерея',
                'verbose_name_plural': 'Галерея',
            },
        ),
        migrations.CreateModel(
            name='CourseStudyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название раздела')),
                ('section_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название раздела')),
                ('section_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название раздела')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание раздела')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Описание раздела')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Описание раздела')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sections', to='codifyteens.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'План обучения',
                'verbose_name_plural': 'План обучения',
            },
        ),
        migrations.CreateModel(
            name='CourseProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/', verbose_name='Проект')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание проекта')),
                ('description_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание проекта')),
                ('description_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание проекта')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='codifyteens.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Пример работ',
                'verbose_name_plural': 'Примеры работ',
            },
        ),
    ]
